# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kmx < Formula
  desc "Agent Builder CLI for Kubernetes"
  homepage "https://github.com/kaimahi-agents/kaimahi"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaimahi-agents/kaimahi/releases/download/v0.4.1/kmx-darwin-amd64"
      sha256 "7bb86da8a036a57716b7fc79ef06410a007da9c2aa699f95b58a1221a8d1f3aa"

      define_method(:install) do
        bin.install "kmx-darwin-amd64" => "kmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaimahi-agents/kaimahi/releases/download/v0.4.1/kmx-darwin-arm64"
      sha256 "7b00909ed199a8beb9c557316737db68488945f4850248a520981034549b946f"

      define_method(:install) do
        bin.install "kmx-darwin-arm64" => "kmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaimahi-agents/kaimahi/releases/download/v0.4.1/kmx-linux-amd64"
      sha256 "b5d6f24eaf06004f69d010e03d8f79352ae0ad2c4ae27bebf542840ae11971d0"
      define_method(:install) do
        bin.install "kmx-linux-amd64" => "kmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaimahi-agents/kaimahi/releases/download/v0.4.1/kmx-linux-arm64"
      sha256 "ae6a27c656804311341eb0c8adf3f1129dfb92fee1cea53f344ec89ba5e44295"
      define_method(:install) do
        bin.install "kmx-linux-arm64" => "kmx"
      end
    end
  end

  test do
    assert_equal "kmx v#{version} (release build)",
                 shell_output("#{bin}/kmx version").lines.first.chomp
    assert_match "Create, inspect, and chat with Orka agents",
                 shell_output("#{bin}/kmx agent --help")
  end
end
